// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMZgLFOSqilTVE7RG0-eKzxmJC2cl8YA',
    appId: '1:1002476805357:web:447d731dc2e749961300e4',
    messagingSenderId: '1002476805357',
    projectId: 'chat-app-229ce',
    authDomain: 'chat-app-229ce.firebaseapp.com',
    storageBucket: 'chat-app-229ce.appspot.com',
    measurementId: 'G-29LXMZFXFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAukqTXDxqCZDPrUu4IPnI5v_KPLDyg0LA',
    appId: '1:1002476805357:android:40fb5e1d6fb572e11300e4',
    messagingSenderId: '1002476805357',
    projectId: 'chat-app-229ce',
    storageBucket: 'chat-app-229ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByiKs9sMu_PxkFHTc4GDjpQUpfIsLzolU',
    appId: '1:1002476805357:ios:70cd46864c1243dc1300e4',
    messagingSenderId: '1002476805357',
    projectId: 'chat-app-229ce',
    storageBucket: 'chat-app-229ce.appspot.com',
    iosClientId: '1002476805357-3i11r5sg82lr42t933b0ech8dr4muc87.apps.googleusercontent.com',
    iosBundleId: 'com.example.communicationChat',
  );
}
